USE [master]
GO

/****** Object:  Database [DB_Tracking]    Script Date: 1/27/2020 11:49:23 PM ******/
CREATE DATABASE [DB_Tracking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_Tracking', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_Tracking.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_Tracking_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_Tracking_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_Tracking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_Tracking] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_Tracking] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_Tracking] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_Tracking] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_Tracking] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_Tracking] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_Tracking] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_Tracking] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_Tracking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_Tracking] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_Tracking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_Tracking] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_Tracking] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_Tracking] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_Tracking] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_Tracking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_Tracking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_Tracking] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_Tracking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_Tracking] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_Tracking] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_Tracking] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_Tracking] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_Tracking] SET  MULTI_USER 
GO

ALTER DATABASE [DB_Tracking] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_Tracking] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_Tracking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_Tracking] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_Tracking] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_Tracking] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DB_Tracking] SET  READ_WRITE 
GO


